#Hotstring
; Ich kann keine Gewähr für diese Liste übernehmen
; Andreas Borutta

; Autokorrekturliste von Jens Arne Maennig

::abeiten::arbeiten
::Abnachung::Abmachung
::Accesoir::Accessoire
::Acksessoir::Accessoire
::adnere::andere
::adneren::anderen
::adneres::anderes
::adners::anders
::Aksessoir::Accessoire
::aler::aller
::anderne::andere
::arbete::arbeite
::arbeten::arbeiten
::arbetest::arbeitest
::arbetet::arbeitet
::Argumnet::Argument
::Assessoir::Accessoire
::auslandisch::ausländisch
::Auswal::Auswahl
::awr::war
::beerits::bereits
::befor::bevor
::bekant::bekannt
::Bekante::Bekannte
::Bekanter::Bekannter
::bekantes::bekanntes
::Belästignug::Belästigung
::Belätsigung::Belästigung
::bereis::bereits
::Bescherde::Beschwerde
::bescämen::beschämen
::Bibliotekh::Bibliothek
::Bibliothrk::Bibliothek
::Blästigung::Belästigung
::brauchenicht::brauche nicht
::brauchstnicht::brauchst nicht
::brauchtnicht::braucht nicht
::Buchsabe::Buchstabe
::Buchstbae::Buchstabe
::dachet::dachte
::daselbe::dasselbe
::Datein::Dateien
::dei::die
::deis::dies
::deise::diese
::deiser::dieser
::dekne::denke
::deknst::denkst
::dersselbe::derselbe
::diesre::dieser
::diesselbe::dieselbe
::dirr::dir
::dise::diese
::disees::dieses
::diser::dieser
::Dnak::Dank
::dnake::danke
::Dockument::Dokument
::Dokkument::Dokument
::Dokumnet::Dokument
::edr::der
::ehielt::erhielt
::emfehlen::empfehlen
::empfelen::empfehlen
::empfelhen::empfehlen
::enige::einige
::eniges::einiges
::enldich::endlich
::Entwicklug::Entwicklung
::Enwicklung::Entwicklung
::ereichen::erreichen
::ereicht::erreicht
::Erflg::Erfolg
::erhalen::erhalten
::erhaltn::erhalten
::erhlaten::erhalten
::erinern::erinnern
::erkennn::erkennen
::erknennen::erkennen
::erts::erst
::fandn::fanden
::fiden::finden
::findn::finden
::Firna::Firma
::fnad::fand
::fnaden::fanden
::fnadst::fandst
::Fnester::Fenster
::folgn::folgen
::folgnd::folgend
::follgen::folgen
::follgend::folgend
::follgende::folgende
::follgender::folgender
::follgendes::folgendes
::Forfall::Vorfall
::fpr::für
::Fra::Frau
::Fraeg::Frage
::fragn::fragen
::Freudne::Freunde
::Freundinen::Freundinnen
::Frima::Firma
::fsat::fast
::fäöschlich::fälschlich
::Garanti::Garantie
::Garrantie::Garantie
::Gechichte::Geschichte
::Gecshichte::Geschichte
::Gefar::Gefahr
::Geidcht::Gedicht
::Gelegenhet::Gelegenheit
::Gelgenheit::Gelegenheit
::geradde::gerade
::Geschichtne::Geschichten
::Geshichte::Geschichte
::ghen::gehen
::ghest::gehst
::glaben::glauben
::glaubn::glauben
::gnaz::ganz
::Grupe::Gruppe
::gschehen::geschehen
::habenicht::habe nicht
::habn::haben
::haett::hatte
::hastnicht::hast nicht
::hatnicht::hat nicht
::hbe::habe
::hoffendlich::hoffentlich
::hst::hast
::Htp::http
::Http::http
::http:\\::http://
::huete::heute
::Hypotek::Hypothek
::ien::ein
::iene::eine
::ienes::eines
::ienige::einige
::ieniges::einiges
::ieronisch::ironisch
::ihc::ich
::imer::immer
::inRichtung::in Richtung
::interrim::interim
::Intriege::Intrige
::intriegieren::intrigieren
::Intrife::Intrige
::ires::ihres
::Jare::Jahre
::jettz::jetzt
::jezt::jetzt
::Jhar::Jahr
::kalrer::klarer
::kan::kann
::kien::kein
::kiene::keine
::kienes::keines
::kiense::keines
::klin::klein
::klint::klingt
::klnnen::können
::klr::klar
::klra::klar
::kna::kann
::Komite::Komitee
::Komittee::Komitee
::Kommitee::Komitee
::Kommittee::Komitee
::Kompreßion::Kompression
::komunizieren::kommunizieren
::konte::konnte
::koonte::konnte
::Kopei::Kopie
::Kres::Kreis
::könte::könnte
::Labaratorium::Laboratorium
::Labbor::Labor
::Labohratorium::Laboratorium
::lebn::leben
::Leistnug::Leistung
::Leistug::Leistung
::Leisung::Leistung
::Lestung::Leistung
::Libe::Liebe
::Liestung::Leistung
::Lizentz::Lizenz
::Luete::Leute
::macen::machen
::machn::machen
::macst::machst
::Mact::Macht
::macte::machte
::magts::magst
::Mathemaitk::Mathematik
::Mathematikk::Mathematik
::Mathemetik::Mathematik
::Mathrmatik::Mathematik
::Mattematik::Mathematik
::mene::meine
::Mesnchen::Menschen
::mga::mag
::michselbst::mich selbst
::mirselbst::mir selbst
::mocte::mochte
::mti::mit
::möcht::möchte
::nachste::nächste
::nachster::nächster
::nachstes::nächstes
::nciht::nicht
::nehmem::nehmen
::nemen::nehmen
::Nihcte::Nichte
::nimst::nimmst
::nltig::nötig
::Nunner::Nummer
::nurr::nur
::nähmlich::nämlich
::nätig::nötig
::Nörigung::Nötigung
::oaky::okay
::ofenbar::offenbar
::ofensichtlich::offensichtlich
::offensicgtlich::offensichtlich
::offensichylich::offensichtlich
::pber::über
::pbertreiben::übertreiben
::Piknick::Picknick
::Piknik::Picknick
::Porblem::Problem
::Porzelan::Porzellan
::Porzellam::Porzellan
::Porzellna::Porzellan
::Potzellan::Porzellan
::Prioität::Priorität
::priorität::Priorität
::Problen::Problem
::Prozellan::Porzellan
::Psycgologie::Psychologie
::Rechnug::Rechnung
::Rekrod::Rekord
::Rhytmus::Rhythmus
::Rythmus::Rhythmus
::Rytmus::Rhythmus
::Sachem::Sachen
::Sahce::Sache
::schonn::schon
::schrebe::schreibe
::schrebst::schreibst
::schreibn::schreiben
::schriben::schreiben
::scon::schon
::Seckretärin::Sekretärin
::seinse::seines
::Sekretätin::Sekretärin
::seperat::separat
::serh::sehr
::seteht::steht
::sgf::Sehr geehrte Frau
::sgdh::Sehr geehrte Damenund Herren
::sgh::Sehr geehrter Herr
::sien::sein
::siene::seine
::sienem::seinem
::sienes::seines
::sioe::sie
::slebst::selbst
::solte::sollte
::solten::sollten
::soltest::solltest
::sparch::sprach
::spircht::spricht
::sprechn::sprechen
::sprischt::sprichst
::steen::stehen
::stpo::stopp
::Stärkke::Stärke
::synonüm::synonym
::sünonym::synonym
::sünonüm::synonym
::tirnkst::trinkst
::tnu::tun
::Traume::Träume
::trinkn::trinken
::trint::trinkt
::täusvhen::täuschen
::uas::aus
::udn::und
::umbedingt::unbedingt
::Unabhägnigkeit::Unabhängigkeit
::Unabhängigket::Unabhängigkeit
::Unahangigkeit::Unabhängigkeit
::unbdingt::unbedingt
::unbedinkt::unbedingt
::unbedint::unbedingt
::unddas::unddas
::undder::undder
::unddie::unddie
::unrerbringen::unterbringen
::unterbingen::unterbringen
::Unterbingung::Unterbringung
::Unterbrignug::Unterbringung
::unzufriden::unzufrieden
::veilleicht::vielleicht
::Versamlung::Versammlung
::vieleicht::vielleicht
::Vorang::Vorrang
::Vorfal::Vorfall
::Vorvall::Vorfall
::vuchstabieren::buchstabieren
::wachesn::wachsen
::wasist::wasist
::wechle::welche
::wechler::welcher
::wechles::welches
::wedre::werde
::wei::wie
::weider::wieder
::weisst::weißt
::weng::wenig
::wenge::wenige
::werd::wird
::Wge::Weg
::Widnows::Windows
::wiel::weil
::wieß::weiß
::wieße::weiße
::wießt::weißt
::wiklich::wirklich
::wil::will
::wilst::willst
::wisen::wissen
::wissn::wissen
::wolen::wollen
::wolltn::wollten
::wolte::wollte
::wolten::wollten
::woltest::wolltest
::woolten::wollten
::wra::war
::wre::wer
::wri::wir
::wriklich::wirklich
::wriklih::wirklich
::Wrot::Wort
::wüdre::würde
::wüdren::würden
::würdst::würdest
::zeigem::zeigen
::Zeti::Zeit
::Zite::Zeit
::Zuhschauer::Zuschauer
::Zuhärer::Zuhörer
::zuruck::zurück
::zürück::zurück
::änlich::ähnlich
::übertreibn::übertreiben
::übetrreiben::übertreiben
::ühnlich::ähnlich